"""`tiles.h` and `tiles.c`: a project's terrain artwork, as C.

The same two-file split `sprite_header.py` explains at length, for the same
reason: `tiles.h` is included by both `platform.c` (which implements
`plat_tile`) and the program's own `main.c`, so it carries `#define`s and
`extern` declarations only -- a definition with a body there would make the
linker see two of every table. The bytes live in `tiles.c`, compiled once.

What is *not* here is the interesting part. A sprite needs a mask array, a
frame count and a precomputed offset table; a tile needs none of the three. It
has one pose because terrain does not animate, and it has no mask because
terrain is the background rather than something drawn over it (see
`spriting.pack_spectrum_tile`). So `tiles.c` is two tables -- the pixels and
one attribute byte per tile -- and the blitter indexes both with the tile
number directly, with no arithmetic at all: not even the `sprite_frame_offset`
lookup that exists to keep a 16-bit multiply out of the generated program.
"""

from __future__ import annotations

from dataclasses import dataclass

from .spriting import TILE_SIZE, PackedTile

_GUARD = "LLMZ80_TILES_H"

#: Bytes per output line in the data arrays, matching `sprite_header.py`'s own
#: `_BYTES_PER_LINE`: purely cosmetic, and chosen the same so the two generated
#: files read alike side by side.
_BYTES_PER_LINE = 16

_BANNER = (
    "/* Generated by llmz80.studio.tile_header -- do not edit by hand.\n"
    " *\n"
    " * One 8x8 block per kind of terrain the design gave artwork to. A tile has\n"
    " * no mask (it is the background, not something drawn over it) and no frames\n"
    " * (terrain does not animate), so plat_tile indexes tile_data[] with the tile\n"
    " * number and needs no offset arithmetic at all. */"
)


def _checked_id(tile_id: str) -> str:
    """`tile_id` if C can spell it, which is not a given: a tile's id comes
    from the design's own vocabulary and reaches C both as a `#define` suffix
    and as a variable-name fragment. Reuses `sprite_header`'s rule rather than
    restating it, so one id is legal in exactly one place."""
    from .sprite_header import _checked_id as checked_sprite_id

    return checked_sprite_id(tile_id)


def _c_byte_array(name: str, data: bytes) -> str:
    if not data:
        raise ValueError(f"tile {name!r} has no packed bytes")
    lines = []
    for start in range(0, len(data), _BYTES_PER_LINE):
        chunk = data[start : start + _BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk) + ",")
    body = "\n".join(lines)
    return f"static const unsigned char {name}[] = {{\n{body}\n}};"


@dataclass(frozen=True)
class _Layout:
    """The shape `tiles.h` and `tiles.c` must agree on, computed once from the
    same dict both renderers are handed."""

    ids: list[str]
    count: int
    bytes_wide: int


def _layout(tiles: dict[str, PackedTile]) -> _Layout:
    ids = [_checked_id(tile_id) for tile_id in tiles]
    widths = {packed.width_bytes for packed in tiles.values()}
    if len(widths) > 1:
        raise ValueError(
            f"tiles disagree on width_bytes ({sorted(widths)}); TILE_BYTES_WIDE can only "
            "hold one value, so a header cannot mix tiles packed for different platforms "
            "or video modes"
        )
    # Never read when TILE_COUNT is 0 (the blitter is compiled out), so the
    # placeholder only has to be a number: 1 is the Spectrum's own width.
    return _Layout(ids=ids, count=len(ids), bytes_wide=next(iter(widths), 1))


def render_tile_header(tiles: dict[str, PackedTile]) -> str:
    """Render `tiles.h` from a project's packed tiles, keyed by tile id.

    Numbered in dictionary order -- insertion order, not alphabetical -- so
    `TILE_<ID>` matches the row of `tile_data[]` the matching
    `render_tile_source` call emits.
    """
    layout = _layout(tiles)

    lines = [f"#ifndef {_GUARD}", f"#define {_GUARD}", _BANNER, ""]
    for index, tile_id in enumerate(layout.ids):
        lines.append(f"#define TILE_{tile_id.upper()} {index}")
    lines.append(f"#define TILE_COUNT {layout.count}")
    lines.append(f"#define TILE_BYTES_WIDE {layout.bytes_wide}")
    lines.append(f"#define TILE_HEIGHT {TILE_SIZE}")
    lines.append("")

    if layout.count == 0:
        lines.append(f"#endif /* {_GUARD} */")
        return "\n".join(lines) + "\n"

    lines.append("#if TILE_COUNT > 0")
    lines.append("")
    lines.append("/* Defined once, in tiles.c -- see that file for why. */")
    lines.append("extern const unsigned char *const tile_data[];")
    lines.append("extern const unsigned char tile_attribute[];")
    lines.append("")
    lines.append("#endif /* TILE_COUNT */")
    lines.append("")
    lines.append(f"#endif /* {_GUARD} */")
    return "\n".join(lines) + "\n"


def render_tile_source(tiles: dict[str, PackedTile]) -> str:
    """Render `tiles.c`: where a project's tile pixels are actually defined."""
    layout = _layout(tiles)

    lines = [_BANNER, "", '#include "tiles.h"', ""]

    if layout.count == 0:
        # Same trap `sprites.c` records: a translation unit holding nothing but
        # an #include is empty as far as z88dk's cc1 is concerned, it says so,
        # and Studio's build policy treats a warning from its own generated
        # source as build-breaking. One inert typedef costs nothing and claims
        # nothing about tiles that do not exist.
        lines.append("typedef int llmz80_tiles_c_is_not_an_empty_translation_unit;")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append("#if TILE_COUNT > 0")
    lines.append("")
    for tile_id, packed in tiles.items():
        lines.append(_c_byte_array(f"tile_{tile_id}_data", packed.data))
        lines.append("")

    pointers = ", ".join(f"tile_{tile_id}_data" for tile_id in layout.ids)
    lines.append(f"const unsigned char *const tile_data[] = {{ {pointers} }};")
    lines.append("")

    # One Spectrum attribute byte per tile (`spriting.pack_spectrum_tile`), so a
    # design's declared tile colour survives all the way to the cell. The CPC
    # blitter ignores this array -- its colour is in the pixels -- but the array
    # exists on both targets so one generated program compiles against either
    # platform library, exactly as `sprite_attribute[]` does.
    attributes = ", ".join(str(tiles[tile_id].attribute) for tile_id in layout.ids)
    lines.append(f"const unsigned char tile_attribute[] = {{{attributes}}};")
    lines.append("")
    lines.append("#endif /* TILE_COUNT */")
    return "\n".join(lines) + "\n"
