import json
from pathlib import Path

import pytest
from PIL import Image

from llmz80.studio.codegen import (
    BEHAVIOUR_CHASE,
    BEHAVIOUR_GUARD,
    BEHAVIOUR_PATROL_H,
    BEHAVIOUR_PATROL_V,
    CELL_COLLECTIBLE,
    audio_mask,
    build_actors,
    spawn_table,
    tile_bitmaps,
)
from llmz80.studio.editing import add_entity, set_audio, set_entity_behaviour, set_entity_count
from llmz80.studio.layout import relayout
from llmz80.studio.compiler import render_project
from llmz80.studio.models import GenreId, TargetPlatform
from llmz80.studio.packs import create_default_project
from llmz80.studio.store import ProjectStore
from llmz80.studio.services import StudioService


@pytest.mark.parametrize("platform", list(TargetPlatform))
def test_rendered_project_is_deterministic_and_owned(tmp_path: Path, platform: TargetPlatform):
    project = create_default_project("Commercial Test", platform, GenreId.MAZE_CHASE)
    directory = ProjectStore(tmp_path).create(project)

    first = render_project(project, directory / "build")
    source = first.main_c.read_text(encoding="utf-8")
    second = render_project(project, directory / "build")

    assert second.main_c.read_text(encoding="utf-8") == source
    assert "Generated by LLMZ80 Studio" in source
    assert (directory / "build" / "design" / "game.yml").is_file()
    manifest = json.loads((directory / "build" / "studio_manifest.json").read_text())
    assert manifest["source_of_truth"] == "game.yml"
    assert manifest["target"] == platform.value


def test_target_platform_layers_use_certified_runtime_calls(tmp_path: Path):
    spectrum = create_default_project("ZX", TargetPlatform.SPECTRUM, GenreId.SINGLE_SCREEN_COLLECT)
    cpc = create_default_project("CPC", TargetPlatform.AMSTRAD_CPC, GenreId.SINGLE_SCREEN_COLLECT)

    zx_dir = render_project(spectrum, tmp_path / "zx").output_dir / "src"
    cpc_dir = render_project(cpc, tmp_path / "cpc").output_dir / "src"
    zx_platform = (zx_dir / "platform.c").read_text()
    cpc_platform = (cpc_dir / "platform.c").read_text()

    assert "in_key_pressed(IN_KEY_SCANCODE_q)" in zx_platform
    assert "zx_cls(PAPER_BLACK | INK_WHITE)" in zx_platform
    assert "cpct_disableFirmware();" in cpc_platform
    assert "cpct_scanKeyboard_f();" in cpc_platform
    assert "cpct_waitVSYNC();" in cpc_platform

    # Gameplay rules are shared, so neither platform layer may contain them.
    for platform_source in (zx_platform, cpc_platform):
        assert "score" not in platform_source
        assert "lives" not in platform_source

    engine = (zx_dir / "engine.c").read_text()
    assert engine == (cpc_dir / "engine.c").read_text()
    assert "SCORE_PER_COLLECTIBLE" in engine
    assert "LEVEL_COUNT" in engine


def test_engine_represents_many_enemies_and_collectibles(tmp_path: Path):
    project = create_default_project("Crowd", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)
    project.entities[1].count = 3
    project.entities[2].count = 12
    project = relayout(project)

    output_dir = render_project(project, tmp_path / "build").output_dir
    data = (output_dir / "src" / "game_data.c").read_text()

    assert "const unsigned char g_actor_count = 16;" in data
    assert "g_actor_kind[16]" in data
    # 3 levels x 16 actors of spawn data, both axes.
    assert "g_spawn_col[48]" in data
    assert "g_spawn_row[48]" in data


def test_levels_receive_distinct_layouts(tmp_path: Path):
    project = create_default_project("Levels", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)
    actors = build_actors(project)

    table = spawn_table(project, actors)

    assert len(table) == project.gameplay.level_count
    assert table[0] != table[1] and table[1] != table[2]
    for level_positions in table:
        collectibles = [
            position
            for position, actor in zip(level_positions, actors)
            if actor.kind == CELL_COLLECTIBLE
        ]
        assert len(set(collectibles)) == len(collectibles)


def test_score_constant_comes_from_the_design(tmp_path: Path):
    project = create_default_project("Scoring", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)
    project.gameplay.score_per_collectible = 25

    header = (
        render_project(project, tmp_path / "build").output_dir / "src" / "game_config.h"
    ).read_text()

    assert "#define SCORE_PER_COLLECTIBLE 25" in header


def test_generated_sources_are_byte_identical_across_runs(tmp_path: Path):
    project = create_default_project("Determinism", TargetPlatform.AMSTRAD_CPC, GenreId.MAZE_CHASE)

    first = render_project(project, tmp_path / "build")
    snapshot = {
        path.relative_to(first.output_dir): path.read_bytes()
        for path in first.output_dir.rglob("*.c")
    }
    snapshot.update(
        {
            path.relative_to(first.output_dir): path.read_bytes()
            for path in first.output_dir.rglob("*.h")
        }
    )
    render_project(project, tmp_path / "build")

    for relative, content in snapshot.items():
        assert (first.output_dir / relative).read_bytes() == content, relative


@pytest.mark.parametrize("platform", list(TargetPlatform))
def test_imported_asset_is_owned_padded_and_target_packed(tmp_path: Path, platform: TargetPlatform):
    source = tmp_path / "odd sprite.png"
    Image.new("RGB", (7, 5), "white").save(source)
    workspace = tmp_path / "projects"
    service = StudioService.at(workspace)
    project, directory = service.create_project("Assets", platform, GenreId.SINGLE_SCREEN_COLLECT)

    asset = service.add_asset(project, directory, source)
    result = service.generate_sources(project, directory)

    assert asset.source.startswith("assets/")
    assert (directory / asset.source).is_file()
    assert (result.output_dir / "src" / "assets.c").is_file()
    header = (result.output_dir / "src" / "assets.h").read_text()
    expected_bytes = 1 if platform is TargetPlatform.SPECTRUM else 2
    assert f"WIDTH_BYTES {expected_bytes}" in header


def test_backend_rejects_a_level_larger_than_the_target_grid(tmp_path: Path):
    project = create_default_project("Oversized", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)
    project = relayout(project, width=40)

    with pytest.raises(ValueError, match="offers 32x22 playable cells"):
        render_project(project, tmp_path / "build")


def test_backend_rejects_more_actors_than_the_entity_budget(tmp_path: Path):
    project = create_default_project("Crowded", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)
    project.budgets.max_entities = 4

    with pytest.raises(ValueError, match="exceeds the max_entities budget"):
        render_project(project, tmp_path / "build")


def test_wall_bitmap_matches_the_authored_terrain(tmp_path: Path):
    project = create_default_project("Walls", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)

    packed, offsets = tile_bitmaps(project)

    assert len(offsets) == len(project.levels)
    for index, level in enumerate(project.levels):
        bits = []
        for byte in packed[offsets[index]:offsets[index] + (level.width * level.height + 7) // 8]:
            bits.extend((byte >> (7 - position)) & 1 for position in range(8))
        for row in range(level.height):
            for col in range(level.width):
                expected = 1 if level.tiles[row][col] == "#" else 0
                assert bits[row * level.width + col] == expected, (level.id, col, row)


def test_generated_data_declares_the_wall_tables(tmp_path: Path):
    project = create_default_project("Tables", TargetPlatform.AMSTRAD_CPC, GenreId.MAZE_CHASE)

    output_dir = render_project(project, tmp_path / "build").output_dir
    data = (output_dir / "src" / "game_data.c").read_text()
    header = (output_dir / "src" / "game_config.h").read_text()

    assert "const unsigned char g_wall_bits[" in data
    assert "const unsigned int g_wall_offset[3]" in data
    assert "#define MAX_LEVEL_HEIGHT 16" in header


def test_designed_behaviours_reach_the_generated_table(tmp_path: Path):
    project = create_default_project("Brains", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)
    project = set_entity_behaviour(project, "enemy", "chase")
    project = add_entity(project, "guard", "enemy", count=1)
    project = set_entity_behaviour(project, "guard", "guard")

    actors = build_actors(project)
    behaviours = {actor.source_id: actor.behaviour for actor in actors}

    assert behaviours["enemy"] == BEHAVIOUR_CHASE
    assert behaviours["guard"] == BEHAVIOUR_GUARD
    output_dir = render_project(project, tmp_path / "build").output_dir
    data = (output_dir / "src" / "game_data.c").read_text()
    assert f"{BEHAVIOUR_CHASE}" in data.split("g_actor_behaviour")[1].split("}")[0]


def test_auto_behaviour_keeps_the_historical_alternation(tmp_path: Path):
    project = create_default_project("Auto", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)
    project = set_entity_count(project, "enemy", 2)

    behaviours = [actor.behaviour for actor in build_actors(project) if actor.source_id == "enemy"]

    assert behaviours == [BEHAVIOUR_PATROL_H, BEHAVIOUR_PATROL_V]


def test_audio_mask_follows_the_designed_effects(tmp_path: Path):
    project = create_default_project("Sound", TargetPlatform.SPECTRUM, GenreId.MAZE_CHASE)

    # AUDIO_EFFECTS order is start, collect, hit, level, game_over.
    assert audio_mask(set_audio(project, effects=["start"])) == 0b00001
    assert audio_mask(set_audio(project, effects=["hit", "game_over"])) == 0b10100
    assert audio_mask(set_audio(project, effects=[])) == 0

    header = (
        render_project(project, tmp_path / "build").output_dir / "src" / "game_config.h"
    ).read_text()
    assert "#define AUDIO_EFFECT_MASK 7" in header


def test_a_silent_target_still_compiles_the_sound_entry_point(tmp_path: Path):
    project = create_default_project("Mute", TargetPlatform.AMSTRAD_CPC, GenreId.MAZE_CHASE)

    source = render_project(project, tmp_path / "build").output_dir / "src"

    assert "#define AUDIO_EFFECT_MASK 0" in (source / "game_config.h").read_text()
    assert "void plat_sound(" in (source / "platform.c").read_text()
