///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music.aks
/// Generation time: mar 11 mar 2025 12:30:22 CET
///

/// Song 'g_music' metadata macros
#define g_music_address  0x2A41
#define g_music_size     5567
#define g_music_end      0x3fff

/// Song 'g_music' array declaration
extern void g_music[g_music_size];
